# Generated by Django 3.2.9 on 2021-11-01 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='ein',
            field=models.CharField(default='570425826', max_length=20),
        ),
    ]
