# Generated by Django 3.2.9 on 2021-11-02 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0002_contribution_ein'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='in_dollars',
            field=models.IntegerField(blank=True, default=20),
        ),
        migrations.AddField(
            model_name='contribution',
            name='in_hours',
            field=models.IntegerField(blank=True, default=2),
        ),
    ]
