# Generated by Django 3.2.9 on 2021-11-02 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0003_auto_20211102_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='contribution',
            name='charity',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='contribution',
            name='ein',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
