# Generated by Django 3.2.9 on 2021-11-06 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0005_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='phase',
            field=models.CharField(choices=[('SUB', 'Submitted'), ('PUB', 'Published')], default='SUB', max_length=3),
        ),
    ]
