# Generated by Django 3.2.9 on 2021-11-11 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0007_alter_contribution_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='review_images'),
        ),
    ]
