# Generated by Django 3.2.9 on 2021-11-12 00:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0008_review_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Charity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('ein', models.CharField(max_length=20)),
                ('url', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='review',
            name='charity',
        ),
    ]
