# Generated by Django 3.2.9 on 2021-11-12 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0009_auto_20211112_0030'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='charity',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='charities.charity'),
        ),
    ]
