# Generated by Django 3.2.9 on 2021-11-12 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0010_review_charity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contribution',
            name='charity',
            field=models.ForeignKey(blank=True, default=None, on_delete=django.db.models.deletion.CASCADE, to='charities.charity'),
        ),
    ]
