# Generated by Django 3.2.9 on 2021-11-14 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0012_auto_20211112_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, default=None, null=True, upload_to='review_images'),
        ),
    ]
