# Generated by Django 3.2.9 on 2021-11-14 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('charities', '0014_alter_review_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='image',
            field=models.ImageField(blank=True, default='usericon.png', upload_to='review_images'),
        ),
    ]
